version: '3.8'
services:
    postgres_db:
        image: postgres:13.5
        container_name: SimpleMinimalAPI
        restart: always
        environment:
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=admin123
            - POSTGRES_DB=minimal_db
        volumes:
            - postgres_db:/var/lib/postgresql/data
            - ./document:/docker-entrypoint-initdb.d
        ports:
            - '5434:5432'
    rabbitmq:
        container_name: "rabbitmq"
        image: rabbitmq:3.8-management-alpine
        environment:
            - RABBITMQ_DEFAULT_USER=user
            - RABBITMQ_DEFAULT_PASS=mypass
        ports:
            # RabbitMQ Instance
            - '5672:5672'
            # Web interface
            - '15672:15672'
volumes:
    postgres_db:
        driver: local