version: '3.8'
services:
    postgres_db:
        image: postgres:13.5
        container_name: SimpleMinimalAPI
        restart: always
        environment:
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=admin123
            - POSTGRES_DB=minimal_db
        volumes:
            - postgres_db:/var/lib/postgresql/data
            - ./document:/docker-entrypoint-initdb.d
        ports:
            - '5434:5432'
volumes:
    postgres_db:
        driver: local